version: '3.8'
services:
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - "80:80"
    # environment:
    #   BACKEND_URL: "http://backend:5000"
    # volumes:
      #mounting directly for development so that restarting isnt needed
      # - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf.template
    networks:
      - app-network

  backend:
    image: backend:latest
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
